### ISSUE TITLE
npm install does not work

### ISSUE THREAD

**Issue by arecker** [jonnypolite/vim-things#1]
hi there

npm install does not work in the repo.  npm says it cannot find the package.json file.  Where do I get it?

**Comment by jonnypolite** [comment]
My apologies for the oversight. If you create your own package.json file and paste the following into it you should be good to go.

```
{
  "name": "vim-things",
  "version": "1.0.0",
  "description": "",
  "main": "rofl.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lol": "^1.0.101-lol"
  }
}
```

**Comment by arecker** [comment]
thank u this worked now I can make your vim config into an electron desktop application ;) 💯
